# Generated by Django 6.0.1 on 2026-03-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
    ]
